- hosts: localhost
  connection: local
  tasks:
  - name: Create (or update) MariaDB Server
    azure_rm_mariadbserver:
      resource_group: "{{ resourcegroupname }}"
      name: "{{ dbservername }}"
      sku:
        name: "{{ dbtiername }}"
        tier: "{{ dbtiertype }}"
      location: "{{ location }}"
      storage_mb: "{{ dbstorage }}"
      enforce_ssl: True
      version: "{{ dbversion }}"
      admin_username: "{{ dbserveradminusername }}"
      admin_password: "{{ dbserveradminpassword }}"
  - name: Create (or update) MariaDB firewall rule
    azure_rm_mariadbfirewallrule:
      resource_group: "{{ resourcegroupname }}"
      server_name: "{{ dbservername }}"
      name: "{{ dbrulename }}"
      start_ip_address: "{{ dbrulestartip }}"
      end_ip_address: "{{ dbruleendip }}"