- hosts: localhost
  connection: local
  tasks:
    - name: Creating resource group - "{{ resourcegroupname }}"
      azure_rm_resourcegroup:
        name: "{{ resourcegroupname }}"
        location: "{{ location }}"
      register: rg
    - debug:
        var: rg