- hosts: localhost
  connection: local
  tasks:
  - name: Delete MariaDB Database
    azure_rm_mariadbdatabase:
      resource_group: "{{ resourcegroupname }}"
      server_name: "{{ dbservername }}"
      name: "{{ dbname }}"
      state: absent