- hosts: localhost
  connection: local
  tasks:
  - name: delete a function app
    azure_rm_functionapp:
      resource_group: "{{ resourcegroupname }}"
      name: "{{ functionname }}"
      storage_account: "{{ functionstoragename }}"
      state: absent
  - name: delete storage account
    azure_rm_storageaccount:
      resource_group: "{{ resourcegroupname }}"
      name: "{{ functionstoragename }}"
      force_delete_nonempty: yes
      state: absent
