- hosts: localhost
  connection: local
  tasks:
  - name: delete MariaDB Server
    azure_rm_mariadbserver:
      resource_group: "{{ resourcegroupname }}"
      name: "{{ dbservername }}"
      state: absent