- hosts: localhost
  connection: local
  tasks:
  - name: delete storage account
    azure_rm_storageaccount:
      resource_group: "{{ resourcegroupname }}"
      name: "{{ storagename }}"
      state: absent
